CREATE OR REPLACE FUNCTION SINGTEL_AMACS_INSERT(P_TIME_ZONE VARCHAR2 DEFAULT NULL)
RETURN INTEGER
IS
L_LOAD_START_DT DATE;
L_LOAD_END_DT DATE;
LOADID INTEGER;
RETVAL INTEGER;
ADAPTER_ID INTEGER := 10;
TZ VARCHAR2(50) := P_TIME_ZONE;
BEGIN
IF TZ IS NULL
THEN
    TZ := DBTIMEZONE;
ELSIF TZ IS NOT NULL
THEN  
    TZ := DBTIMEZONE;
ELSE
    TZ := NULL;
END IF;

SELECT
  MIN(FROM_TZ(CALL_DATE
   + NUMTODSINTERVAL(EXTRACT (HOUR FROM DISCONNECT_TIME),'HOUR')
   + NUMTODSINTERVAL(EXTRACT (MINUTE FROM DISCONNECT_TIME),'MINUTE')
   + NUMTODSINTERVAL(EXTRACT (SECOND FROM DISCONNECT_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT'),
  MAX(FROM_TZ(CALL_DATE
   + NUMTODSINTERVAL(EXTRACT (HOUR FROM DISCONNECT_TIME),'HOUR')
   + NUMTODSINTERVAL(EXTRACT (MINUTE FROM DISCONNECT_TIME),'MINUTE')
   + NUMTODSINTERVAL(EXTRACT (SECOND FROM DISCONNECT_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT')
INTO
    L_LOAD_START_DT,
    L_LOAD_END_DT
FROM
  XDV_SINGTEL_AMA_CS_ET;

SELECT XDV_ASM_TRN_SEQ.NEXTVAL INTO LOADID FROM DUAL;

INSERT INTO XDV_ASM_MEDSES_FT
(TAT_ID, TAC_ID, TRC_ID, TRS_ID, TRQ_ID, SRV_ID, DDE_ID, DTE_ID, END_TIME_MS, DURATION, SETUP_DURATION,
DATA_TRANS_DURATION, TEID, USER_AGENT, IMEI, MSISDN, IMSI, NBR_MESSAGES, NBR_BYTES, NBR_CLIENT_COMMANDS,
NBR_BYTES_LOST, JITTER, USER_ID, MAILBOX_NAME, SESSION_ID, TO_RECIPIENT, TO_PATH, TO_VIA_PATH, FROM_ORIGINATOR,
FROM_PATH, FROM_VIA_PATH, SERVER_AGENT, ROUTING_AREA, CELL_IDENTITY, SGSN, GGSN, ACCESS_POINT_NAME, LOAD_ID,
INT_SESSION_ID)
SELECT
  TAT_ID,
  TAC_ID,
  TRC_ID,
  TRS_ID,
  TRQ_ID,
  -1 AS SRV_ID,
  EXTRACT(DAY FROM TIME_INTERVAL) * 86400 + EXTRACT (HOUR FROM TIME_INTERVAL) * 3600 AS DDE_ID,
  EXTRACT(MINUTE FROM TIME_INTERVAL) * 60 + EXTRACT (SECOND FROM TIME_INTERVAL) AS DTE_ID,
  0 AS END_TIME_MS,
  DURATION,
  NULL AS SETUP_DURATION,
  NULL AS DATA_TRANS_DURATION,
  NULL AS TEID,
  NULL AS USER_AGENT,
  IMEI,
  MSISDN,
  IMSI,
  NULL AS NBR_MESSAGES,
  NULL AS NBR_BYTES,
  NULL AS NBR_CLIENT_COMMANDS,
  NULL AS NBR_BYTES_LOST,
  NULL AS JITTER,
  NULL AS USER_ID,
  NULL AS MAILBOX_NAME,
  NULL AS SESSION_ID,
  NULL AS TO_RECIPIENT,
  TO_PATH,
  NULL AS TO_VIA_PATH,
  FROM_ORIGINATOR,
  FROM_PATH,
  MSC_ID AS FROM_VIA_PATH,
  NULL AS SERVER_AGENT,
  -1 AS ROUTING_AREA,
  CELL_IDENTITY,
  -1 AS SGSN,
  -1 AS GGSN,
  NULL AS ACCESS_POINT_NAME,
  LOADID AS LOAD_ID,
  INT_SESSION_ID AS INT_SESSION_ID
FROM
  (SELECT
    NVL(AT_.EXT_ID, 351)  AS TAT_ID,
    NVL(ACT.EXT_ID, -1) AS TAC_ID,
    NVL(CA.ID, -1) AS TRC_ID,
    NVL(ST.EXT_ID, -1) AS TRS_ID,
    -1 AS TRQ_ID,
    (EXTRACT (HOUR FROM EXT.DURATION_)*3600 + EXTRACT (MINUTE FROM EXT.DURATION_)*60 + EXTRACT (SECOND FROM EXT.DURATION_)) * 1000 AS DURATION,
    EXT.IMEI AS IMEI,
    NVL(TRIM(EXT.GSM_SUBSCIBER_NUMBER), -1) AS MSISDN,
    NVL(TRIM(EXT.GSM_SUBSCRIBER_IMSI), -1) AS IMSI,
    EXT.END_CELL_ID AS TO_PATH,
    EXT.PSTN_ROUTE AS FROM_PATH,
    trim(EXT.LAC) AS FROM_ORIGINATOR,
    EXT.START_CELL_ID AS CELL_IDENTITY,
    EXT.MSC_ID AS MSC_ID,
    ((FROM_TZ(CALL_DATE
    + NUMTODSINTERVAL(EXTRACT (HOUR FROM DISCONNECT_TIME),'HOUR')
    + NUMTODSINTERVAL(EXTRACT (MINUTE FROM DISCONNECT_TIME),'MINUTE')
    + NUMTODSINTERVAL(EXTRACT (SECOND FROM DISCONNECT_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT') - C_Y1970)
    DAY (6) TO SECOND(0) AS TIME_INTERVAL,
    EXT.ANSWER_TIME AS ANSWER_TIME,
    EXT.DURATION_ AS CALL_DURATION,
    EXT.DISCONNECT_TIME AS DISCONNECT_TIME,
    10 ||
    to_char(EXT.CALL_DATE,'MMDD') ||
    to_char(EXT.ANSWER_TIME,'HH24MISS') ||
    substr(trim(EXT.GSM_SUBSCIBER_NUMBER), length(trim(EXT.GSM_SUBSCIBER_NUMBER))-2) ||
    substr(trim(EXT.CALL_SEQUENCE_NUMBER), length(trim(EXT.CALL_SEQUENCE_NUMBER))-4)
    AS INT_SESSION_ID
FROM
    XDV_SINGTEL_AMA_CS_ET EXT LEFT JOIN XDV_SINGTEL_AMACS_APP_TYPE_DT AT_
         ON EXT.SERVICE_TYPE = AT_.SERVICE_TYPE
    LEFT JOIN XDV_SINGTEL_AMACS_ACT_DT ACT
         ON EXT.TRAFFIC_CLASS = ACT.TRAFFIC_CLASS
    LEFT JOIN XDV_SINGTEL_AMACS_STATUS_DT ST
         ON EXT.CALL_SETUP_RESULT_CODE = ST.CALL_SETUP_RES_CODE
    LEFT JOIN XDV_TRN_CAUSES_DT CA
         ON (EXT.TERMINATING_REASON = CA.PRIMARY_CAUSE_ID AND CA.INTERFACE = 'AMACS')
);
RETVAL := SQL%ROWCOUNT;

INSERT INTO XDV_ASM_MEDSES_FT
(TAT_ID, TAC_ID, TRC_ID, TRS_ID, TRQ_ID, SRV_ID, DDE_ID, DTE_ID, END_TIME_MS, DURATION, SETUP_DURATION,
DATA_TRANS_DURATION, TEID, USER_AGENT, IMEI, MSISDN, IMSI, NBR_MESSAGES, NBR_BYTES, NBR_CLIENT_COMMANDS,
NBR_BYTES_LOST, JITTER, USER_ID, MAILBOX_NAME, SESSION_ID, TO_RECIPIENT, TO_PATH, TO_VIA_PATH, FROM_ORIGINATOR,
FROM_PATH, FROM_VIA_PATH, SERVER_AGENT, ROUTING_AREA, CELL_IDENTITY, SGSN, GGSN, ACCESS_POINT_NAME, LOAD_ID,
INT_SESSION_ID)
SELECT
  350 AS TAT_ID,
  -1  AS TAC_ID,
  -1  AS TRC_ID,
  -1  AS TRS_ID,
  -1  AS TRQ_ID,
  -1  AS SRV_ID,
  EXTRACT(DAY FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 86400 + EXTRACT(HOUR FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 3600 AS DDE_ID,
  EXTRACT(MINUTE FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 60 + EXTRACT (SECOND FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) AS DTE_ID,
  0  AS END_TIME_MS,
  0  AS DURATION,
  NULL AS SETUP_DURATION,
  NULL AS DATA_TRANS_DURATION,
  NULL AS TEID,
  NULL AS USER_AGENT,
  NULL AS IMEI,
  -1 AS MSISDN,
  -1 AS IMSI,
  NBR_MESSAGES,
  NULL AS NBR_BYTES,
  NULL AS NBR_CLIENT_COMMANDS,
  NULL AS NBR_BYTES_LOST,
  NULL AS JITTER,
  NULL AS USER_ID,
  NULL AS MAILBOX_NAME,
  NULL AS SESSION_ID,
  NULL AS TO_RECIPIENT,
  NULL AS TO_PATH,
  NULL AS TO_VIA_PATH,
  NULL AS FROM_ORIGINATOR,
  NULL AS FROM_PATH,
  NULL AS FROM_VIA_PATH,
  NULL AS SERVER_AGENT,
  NULL AS ROUTING_AREA,
  NULL AS CELL_IDENTITY,
  -1 AS SGSN,
  -1 AS GGSN,
  NULL AS ACCESS_POINT_NAME,
  LOADID AS LOAD_ID,
  INT_SESSION_ID AS INT_SESSION_ID
FROM
  (
    SELECT
     (FROM_TZ(CST.CREATION_DATETIME, TZ) AT TIME ZONE 'GMT' - C_Y1970) DAY (6) TO SECOND(0) AS TIME_INTERVAL,
        CST.DATA_RECORD_COUNT AS NBR_MESSAGES,
        ADAPTER_ID
        	|| to_char(CST.CREATION_DATETIME,'MMDDHH24MISS')
        	|| CST.FILE_SEQ_NO
        	|| CST.FILE_SEQ_NO
        	AS INT_SESSION_ID
    FROM
        XDV_SINGTEL_AMA_CS_TRAILER_ET CST
  );

RETVAL := RETVAL + SQL%ROWCOUNT;


XDV_ADAPTER_PKG.ENQUEUE_LOAD(
    A_QUEUE_NAME => XDV_GENERIC_CONST_PKG.PC_AQ_MED_LOAD_ASM_QNAME,
    A_LOAD_ID => LOADID,
    A_LOAD_ST_TS => L_LOAD_START_DT,
    A_LOAD_END_TS => L_LOAD_END_DT,
    A_SENDER_ID => PC_SNDR,
    A_MESSAGE => 'Message with load-id ' || LOADID || ', enqueued onto ' || XDV_GENERIC_CONST_PKG.PC_AQ_MED_LOAD_ASM_QNAME);
COMMIT;
RETURN RETVAL;
END SINGTEL_AMACS_INSERT;
