CREATE OR REPLACE PACKAGE BODY XDVMED.XDV_ADAPTER_AMAPS_PKG
IS
FUNCTION SINGTEL_AMAPS_INSERT(P_TIME_ZONE VARCHAR2 DEFAULT NULL)
RETURN INTEGER
IS
L_LOAD_START_DT DATE;
L_LOAD_END_DT DATE;
LOADID INTEGER;
RETVAL INTEGER;
ADAPTER_ID INTEGER := 11;
TZ VARCHAR2(50) := P_TIME_ZONE;
BEGIN
IF TZ IS NULL THEN TZ := DBTIMEZONE; END IF;

SELECT
  MIN(FROM_TZ(END_DATE_OF_CALL
   + NUMTODSINTERVAL(EXTRACT (HOUR FROM PDP_CONTEXT_STOP_TIME),'HOUR')
   + NUMTODSINTERVAL(EXTRACT (MINUTE FROM PDP_CONTEXT_STOP_TIME),'MINUTE')
   + NUMTODSINTERVAL(EXTRACT (SECOND FROM PDP_CONTEXT_STOP_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT'),
  MAX(FROM_TZ(END_DATE_OF_CALL
   + NUMTODSINTERVAL(EXTRACT (HOUR FROM PDP_CONTEXT_STOP_TIME),'HOUR')
   + NUMTODSINTERVAL(EXTRACT (MINUTE FROM PDP_CONTEXT_STOP_TIME),'MINUTE')
   + NUMTODSINTERVAL(EXTRACT (SECOND FROM PDP_CONTEXT_STOP_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT')
INTO
	L_LOAD_START_DT,
	L_LOAD_END_DT
FROM
  XDV_SINGTEL_AMA_PS_ET;

SELECT XDV_ASM_TRN_SEQ.NEXTVAL INTO LOADID FROM DUAL;

INSERT INTO XDV_ASM_MEDSES_FT
(TAT_ID, TAC_ID, TRC_ID, TRS_ID, TRQ_ID, SRV_ID, DDE_ID, DTE_ID, END_TIME_MS, DURATION, SETUP_DURATION,
DATA_TRANS_DURATION, TEID, USER_AGENT, IMEI, MSISDN, IMSI, NBR_MESSAGES, NBR_BYTES, NBR_CLIENT_COMMANDS,
NBR_BYTES_LOST, JITTER, USER_ID, MAILBOX_NAME, SESSION_ID, TO_RECIPIENT, TO_PATH, TO_VIA_PATH, FROM_ORIGINATOR,
FROM_PATH, FROM_VIA_PATH, SERVER_AGENT, ROUTING_AREA, CELL_IDENTITY, SGSN, GGSN, ACCESS_POINT_NAME, LOAD_ID,
INT_SESSION_ID)
SELECT
  TAT_ID,
  TAC_ID,
  TRC_ID,
  TRS_ID,
  TRQ_ID,
  SRV_ID,
  EXTRACT(DAY FROM TIME_INTERVAL) * 86400 + EXTRACT (HOUR FROM TIME_INTERVAL) * 3600  AS DDE_ID,
  EXTRACT(MINUTE FROM TIME_INTERVAL) * 60 + EXTRACT (SECOND FROM TIME_INTERVAL) AS DTE_ID,
  0 AS END_TIME_MS,
  NVL(DURATION_, 0) AS DURATION,
  NULL AS SETUP_DURATION,
  NULL AS DATA_TRANS_DURATION,
  NULL AS TEID,
  NULL AS USER_AGENT,
  IMEI,
  MSISDN,
  IMSI,
  NULL AS NBR_MESSAGES,
  NBR_BYTES,
  NULL AS NBR_CLIENT_COMMANDS,
  NBR_BYTES_LOST,
  NULL AS JITTER,
  NULL AS USER_ID,
  NULL AS MAILBOX_NAME,
  NULL AS SESSION_ID,
  NULL AS TO_RECIPIENT,
  NULL AS TO_PATH,
  NULL AS TO_VIA_PATH,
  FROM_ORIGINATOR,
  NULL AS FROM_PATH,
  NULL AS FROM_VIA_PATH,
  SERVER_AGENT,
  NULL AS ROUTING_AREA,
  CELL_IDENTITY,
  NVL(SGSN, -1) AS SGSN,
  NVL(GGSN, -1) AS GGSN,
  ACCESS_POINT_NAME,
  LOADID AS LOAD_ID,
  CAST (INT_SESSION_ID AS INTEGER) AS INT_SESSION_ID
FROM
  (SELECT
    NVL(AT_.EXT_ID, 413)  AS TAT_ID,
    -1 AS TAC_ID,
    (CASE WHEN CA.ID IS NULL OR (EXT.TERMINATING_REASON IS NULL) THEN -1 ELSE CA.ID END) AS TRC_ID,
    (CASE WHEN EXT.TERMINATING_REASON = '00000' THEN 200
		WHEN EXT.TERMINATING_REASON = '24HRS' THEN 202
		WHEN EXT.TERMINATING_REASON IS NULL THEN -1
		ELSE 201 END) AS TRS_ID,
    -1 AS TRQ_ID,
    (CASE EXT.CONTENT_PROVIDER_CODE WHEN '     ' THEN -1
    ELSE
	CAST (EXT.CONTENT_PROVIDER_CODE AS INTEGER) END) AS SRV_ID,
	EXT.CONTENT_PROVIDER_CODE AS SERVER_AGENT,
    (CASE EXT.TOTAL_GGSN_DURATION WHEN '        ' THEN NULL
    ELSE
    CAST (substr(EXT.TOTAL_GGSN_DURATION, 1, 2) AS INTEGER) * 24 * 60 * 60 * 1000
    + CAST(substr(EXT.TOTAL_GGSN_DURATION, 3, 2) AS INTEGER) * 60 * 60 * 1000
    + CAST(substr(EXT.TOTAL_GGSN_DURATION, 5, 2) AS INTEGER) * 60 * 1000
    + CAST(substr(EXT.TOTAL_GGSN_DURATION, 7, 2) AS INTEGER) * 1000 END) AS DURATION_,
    TRIM(EXT.SERVED_IMEI) AS IMEI,
    NVL(TRIM(EXT.GSM_SUBSCRIBER_NUMBER_MSISDN), -1) AS MSISDN,
    NVL(TRIM(EXT.SERVED_IMSI), -1) AS IMSI,
    EXT.TOTAL_GGSN_DOWNLINK_TRAFFIC AS NBR_BYTES,
    EXT.RNC_UNSENT_DOWNLINK_VOLUME AS NBR_BYTES_LOST,
    EXT.FIRST_ROUTING_AREA AS FROM_ORIGINATOR,
    (CASE EXT.FIRST_CELL_ID WHEN '     ' THEN NULL
    ELSE
    CAST (EXT.FIRST_CELL_ID AS INTEGER) END) AS CELL_IDENTITY,
    TRIM(EXT.SGSN_ADDRESS) AS SGSN,
    TRIM(EXT.GGSN_ADDRESS) AS GGSN,
    TRIM(EXT.ACCESS_POINT_NAME_NETWORK_ID) AS ACCESS_POINT_NAME,
    (FROM_TZ(END_DATE_OF_CALL
    + NUMTODSINTERVAL(EXTRACT (HOUR FROM PDP_CONTEXT_STOP_TIME),'HOUR')
    + NUMTODSINTERVAL(EXTRACT (MINUTE FROM PDP_CONTEXT_STOP_TIME),'MINUTE')
    + NUMTODSINTERVAL(EXTRACT (SECOND FROM PDP_CONTEXT_STOP_TIME),'SECOND'), TZ) AT TIME ZONE 'GMT' - C_Y1970)
    DAY (6) TO SECOND(0) AS TIME_INTERVAL,
    EXT.PDP_CONTEXT_STOP_TIME AS PDP_CONTEXT_STOP_TIME,
    11 ||
    to_char(EXT.START_DATE_OF_CALL,'MMDD') ||
    to_char(EXT.PDP_CONTEXT_START_TIME,'HH24MISS') ||
    substr(trim(EXT.GSM_SUBSCRIBER_NUMBER_MSISDN), length(trim(EXT.GSM_SUBSCRIBER_NUMBER_MSISDN))-2) ||
    substr(trim(EXT.CALL_SEQUENCE_NUMBER), length(trim(EXT.CALL_SEQUENCE_NUMBER))-4) AS INT_SESSION_ID
FROM
    XDV_SINGTEL_AMA_PS_ET EXT LEFT JOIN XDV_SINGTEL_AMAPS_APP_TYPE_DT AT_
         ON (EXT.CALL_TYPE = AT_.CALL_TYPE AND EXT.PDP_TYPE = AT_.PDP_TYPE)
    LEFT JOIN XDV_TRN_CAUSES_DT CA
         ON (trim(EXT.TERMINATING_REASON) = CA.PRIMARY_CAUSE_ID AND CA.INTERFACE = 'AMAPS')
);
RETVAL := SQL%ROWCOUNT;

INSERT INTO XDV_ASM_MEDSES_FT
(TAT_ID, TAC_ID, TRC_ID, TRS_ID, TRQ_ID, SRV_ID, DDE_ID, DTE_ID, END_TIME_MS, DURATION, SETUP_DURATION,
DATA_TRANS_DURATION, TEID, USER_AGENT, IMEI, MSISDN, IMSI, NBR_MESSAGES, NBR_BYTES, NBR_CLIENT_COMMANDS,
NBR_BYTES_LOST, JITTER, USER_ID, MAILBOX_NAME, SESSION_ID, TO_RECIPIENT, TO_PATH, TO_VIA_PATH, FROM_ORIGINATOR,
FROM_PATH, FROM_VIA_PATH, SERVER_AGENT, ROUTING_AREA, CELL_IDENTITY, SGSN, GGSN, ACCESS_POINT_NAME, LOAD_ID,
INT_SESSION_ID)
SELECT
  402 AS TAT_ID,
  -1  AS TAC_ID,
  -1  AS TRC_ID,
  -1  AS TRS_ID,
  -1  AS TRQ_ID,
  -1  AS SRV_ID,
  EXTRACT(DAY FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 86400 + EXTRACT(HOUR FROM (TIME_INTERVAL)) * 3600 AS DDE_ID,
  EXTRACT(MINUTE FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 60 + EXTRACT (SECOND FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) AS DTE_ID,
--  EXTRACT(DAY FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 86400 + EXTRACT(HOUR FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 3600 AS DDE_ID,
--  EXTRACT(MINUTE FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) * 60 + EXTRACT (SECOND FROM (TIME_INTERVAL - INTERVAL '30' MINUTE)) AS DTE_ID,
  0 AS END_TIME_MS,
  0 AS DURATION,
  NULL AS SETUP_DURATION,
  NULL AS DATA_TRANS_DURATION,
  NULL AS TEID,
  NULL AS USER_AGENT,
  NULL AS IMEI,
  -1 AS MSISDN,
  -1 AS IMSI,
  NBR_MESSAGES,
  NULL AS NBR_BYTES,
  NULL AS NBR_CLIENT_COMMANDS,
  NULL AS NBR_BYTES_LOST,
  NULL AS JITTER,
  NULL AS USER_ID,
  NULL AS MAILBOX_NAME,
  NULL AS SESSION_ID,
  NULL AS TO_RECIPIENT,
  NULL AS TO_PATH,
  NULL AS TO_VIA_PATH,
  NULL AS FROM_ORIGINATOR,
  NULL AS FROM_PATH,
  NULL AS FROM_VIA_PATH,
  NULL AS SERVER_AGENT,
  NULL AS ROUTING_AREA,
  NULL AS CELL_IDENTITY,
  -1 AS SGSN,
  -1 AS GGSN,
  NULL AS ACCESS_POINT_NAME,
  LOADID,
  INT_SESSION_ID
FROM
  (
    SELECT
    (FROM_TZ(PST.CREATION_DATETIME, TZ) AT TIME ZONE 'GMT' - C_Y1970) DAY (6) TO SECOND(0) AS TIME_INTERVAL,
    PST.RECORD_COUNT_1 AS NBR_MESSAGES,
	ADAPTER_ID
		|| to_char(PST.CREATION_DATETIME,'MMDDHH24MISS')
		|| PST.FILE_SEQ_NO
		|| PST.FILE_SEQ_NO
		AS INT_SESSION_ID
  FROM
    XDV_SINGTEL_AMA_PS_TRAILER_ET PST
  );

RETVAL := RETVAL + SQL%ROWCOUNT;

XDV_ADAPTER_PKG.ENQUEUE_LOAD(
  A_QUEUE_NAME => XDV_GENERIC_CONST_PKG.PC_AQ_MED_LOAD_ASM_QNAME,
  A_LOAD_ID => LOADID,
  A_LOAD_ST_TS => L_LOAD_START_DT,
  A_LOAD_END_TS => L_LOAD_END_DT,
  A_SENDER_ID => PC_SNDR,
  A_MESSAGE => 'Message with load-id ' || LOADID || ', enqueued onto ' || XDV_GENERIC_CONST_PKG.PC_AQ_MED_LOAD_ASM_QNAME);
COMMIT;
RETURN RETVAL;
END SINGTEL_AMAPS_INSERT;
END XDV_ADAPTER_AMAPS_PKG;
/