package com.deepsky.gui2;

import com.intellij.codeInsight.hint.HintUtil;
import com.intellij.openapi.ui.popup.ComponentPopupBuilder;
import com.intellij.openapi.ui.popup.JBPopup;
import com.intellij.openapi.ui.popup.JBPopupFactory;
import com.intellij.openapi.ui.popup.util.MinimizeButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ShowTNSNamesFile {
    private JComboBox comboBox1;
    private JEditorPane editorPane1;
    private JPanel rootPanel;
    private JPanel bottomPanel;


    public ShowTNSNamesFile(String[] aliasNames, String current, String text) {

        editorPane1.setText(text);
        editorPane1.setCaretPosition(0);
        editorPane1.setBackground(HintUtil.INFORMATION_COLOR);
        editorPane1.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));


/*
        for (String o : aliasNames) {
            comboBox1.addItem(o);
        }
        comboBox1.setSelectedItem(current);
*/

        rootPanel.setPreferredSize(new Dimension(600, 300));
    }

    public JPanel getRootComponent() {
        return rootPanel;
    }


    public static JBPopup createTNSNamesPopup(String[] aliasNames, String filePath, String text) {
        final ComponentPopupBuilder builder = JBPopupFactory.getInstance()
                .createComponentPopupBuilder(new ShowTNSNamesFile(null, null, text).getRootComponent(), null);

        return builder.setCancelOnClickOutside(false).setBelongsToGlobalPopupStack(true)
                .setFocusable(true).setMovable(true).setResizable(true)
                .setCancelOnOtherWindowOpen(false).setCancelButton(new MinimizeButton("Hide"))
                .setTitle(filePath)
                .setDimensionServiceKey(null, "TNSFileContentPopup", true).createPopup();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(bottomPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bottomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        final JScrollPane scrollPane1 = new JScrollPane();
        bottomPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        editorPane1 = new JEditorPane();
        editorPane1.setEditable(false);
        scrollPane1.setViewportView(editorPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
