CREATE TABLE XDV_AAI_15M_INTAPA_FT (
    TAT_ID		NUMBER(22),
    TAC_ID		NUMBER(22),
    TRC_ID		NUMBER(22),
    TRS_ID		NUMBER(22),
    TRQ_ID		NUMBER(22),
    DDE_ID		NUMBER(22),
    DTE_ID		NUMBER(22),
    CONSTRAINT XDV_AAI_15M_TRC_FK
        FOREIGN KEY (DTE_ID, DDE_ID, <caret>)
REFERENCES XDV_TRN_CAUSES_DT(ID)
);