CREATE TABLE xtab (col1 varchar2(2000))
ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY data_dir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
PREPROCESSOR execdir:'uncompress.sh'
FIELDS (col1 char(2000)))
LOCATION ('foo.dat.gz'))
 REJECT LIMIT UNLIMITED;