CREATE TABLE "PLN_STATIC"."AIRPORT" (
           "ID" NUMBER(10,0) NOT NULL ENABLE,

                "LOCATIONCODE" VARCHAR2(3 CHAR) NOT NULL ENABLE,

                "CITYCODE" VARCHAR2(3 CHAR),

                "LOCATIONTYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE,

                "LOCATIONNAME" VARCHAR2(256 CHAR) NOT NULL ENABLE,

                "CITYNAME" VARCHAR2(256 CHAR),

                "STATECODE" VARCHAR2(2 CHAR),

                "COUNTRYCODE" VARCHAR2(3 CHAR),

                "COUNTRYNAME" VARCHAR2(256 CHAR),

                "LATITUDE" FLOAT(126) DEFAULT NULL,

                "LONGITUDE" FLOAT(126) DEFAULT NULL,

                "TIMEZONE" VARCHAR2(64 CHAR),

                "PAXCOUNT" NUMBER(10,0) NOT NULL ENABLE,

                 CONSTRAINT "PRIMARY" PRIMARY KEY ("ID")

  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS

  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)

  TABLESPACE "PLN"  ENABLE

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING

  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)

  TABLESPACE "PLN";