CREATE TABLE "EVENTS"."BILLING_EVENTS" (
   ID    INTEGER,
   AIRLINECODE    VARCHAR2(2),
	PNR_CREATIONS		INTEGER,
	PNR_CANCELS		   INTEGER,
	TICKETS		      INTEGER,
	CHECKINS		      INTEGER,
	AVAILABILITIES		INTEGER,
	AIRFARE_SHOPS		INTEGER,
	AIRFARE_PRICES		INTEGER,
	PNR_READS		   INTEGER,
	EMAILS		   INTEGER,
	SMSS		      INTEGER,
	BAGTRACES		INTEGER,
	FLIGHT_STATUS		INTEGER,
	EVENT_TIMESTAMP   DATE,
   CONSTRAINT "BILLING_EVENTS_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
   ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  ;