CREATE TABLE UNDO$ (
	US#		NUMBER(22)	NOT NULL,
	NAME		VARCHAR2(30)	NOT NULL,
	USER#		NUMBER(22)	NOT NULL,
	FILE#		NUMBER(22)	NOT NULL,
	BLOCK#		NUMBER(22)	NOT NULL,
	SCNBAS		NUMBER(22),
	SCNWRP		NUMBER(22),
	XACTSQN		NUMBER(22),
	UNDOSQN		NUMBER(22),
	INST#		NUMBER(22),
	STATUS$		NUMBER(22)	NOT NULL,
	TS#		NUMBER(22),
	UGRP#		NUMBER(22),
	KEEP		NUMBER(22),
	OPTIMAL		NUMBER(22),
	FLAGS		NUMBER(22),
	SPARE1		NUMBER(22),
	SPARE2		NUMBER(22),
	SPARE3		NUMBER(22),
	SPARE4		VARCHAR2(1000),
	SPARE5		VARCHAR2(1000),
	SPARE6		DATE
);
-- Table script is not complete and should be used for referencing only
-- Tablespace and storage parameters are not supported
