
REM ========================================================================
REM This file populates the manifest of database objects (DR$DBO) 
REM which is used by the move procedure, validation procedure, etc.
REM ========================================================================

truncate table ctxsys.dr$dbo;
insert into ctxsys.dr$dbo values ('DR$PARAMETER','TABLE');
insert into ctxsys.dr$dbo values ('DR$CLASS','TABLE');
insert into ctxsys.dr$dbo values ('DR$OBJECT','TABLE');
insert into ctxsys.dr$dbo values ('DR$OBJECT_ATTRIBUTE','TABLE');
insert into ctxsys.dr$dbo values ('DR$OBJECT_ATTRIBUTE_LOV','TABLE');
insert into ctxsys.dr$dbo values ('DR$PREFERENCE','TABLE');
insert into ctxsys.dr$dbo values ('DR$PREFERENCE_VALUE','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_PARTITION','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_VALUE','TABLE');
insert into ctxsys.dr$dbo values ('DR$POLICY_TAB','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_OBJECT','TABLE');
insert into ctxsys.dr$dbo values ('DR$SQE','TABLE');
insert into ctxsys.dr$dbo values ('DR$THS','TABLE');
insert into ctxsys.dr$dbo values ('DR$THS_PHRASE','TABLE');
insert into ctxsys.dr$dbo values ('DR$THS_FPHRASE','TABLE');
insert into ctxsys.dr$dbo values ('DR$THS_BT','TABLE');
insert into ctxsys.dr$dbo values ('DR$SECTION_GROUP','TABLE');
insert into ctxsys.dr$dbo values ('DR$SECTION','TABLE');
insert into ctxsys.dr$dbo values ('DR$STOPLIST','TABLE');
insert into ctxsys.dr$dbo values ('DR$STOPWORD','TABLE');
insert into ctxsys.dr$dbo values ('DR$SUB_LEXER','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_SET','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_SET_INDEX','TABLE');
insert into ctxsys.dr$dbo values ('DR$PENDING','TABLE');
insert into ctxsys.dr$dbo values ('DR$WAITING','TABLE');
insert into ctxsys.dr$dbo values ('DR$ONLINE_PENDING','TABLE');
insert into ctxsys.dr$dbo values ('DR$DELETE','TABLE');
insert into ctxsys.dr$dbo values ('DR$UNINDEXED','TABLE');
insert into ctxsys.dr$dbo values ('DR$INDEX_ERROR','TABLE');
insert into ctxsys.dr$dbo values ('DR$PARALLEL','TABLE');
insert into ctxsys.dr$dbo values ('DR$STATS','TABLE');
insert into ctxsys.dr$dbo values ('DR$NUMBER_SEQUENCE','TABLE');
insert into ctxsys.dr$dbo values ('DR$DBO','TABLE');
insert into ctxsys.dr$dbo values ('DR_ID_SEQ','SEQUENCE');
insert into ctxsys.dr$dbo values ('MESG_ID_SEQ','SEQUENCE');
insert into ctxsys.dr$dbo values ('THS_SEQ','SEQUENCE');
insert into ctxsys.dr$dbo values ('CTX_FEEDBACK_ITEM_TYPE','TYPE');
insert into ctxsys.dr$dbo values ('CTX_FEEDBACK_TYPE','TYPE');
insert into ctxsys.dr$dbo values ('DR$NVTAB','TABLE');
insert into ctxsys.dr$dbo values ('CTX_PARAMETERS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_PARAMETERS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_CLASSES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_CLASSES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_OBJECTS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_OBJECTS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_OBJECT_ATTRIBUTES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_OBJECT_ATTRIBUTES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_OBJECT_ATTRIBUTE_LOV','VIEW');
insert into ctxsys.dr$dbo values ('CTX_OBJECT_ATTRIBUTE_LOV','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_PREFERENCES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_PREFERENCES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_PREFERENCES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_PREFERENCES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_PREFERENCE_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_PREFERENCE_VALUES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_PREFERENCE_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_PREFERENCE_VALUES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEXES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEXES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEXES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_PARTITIONS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_PARTITIONS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_PARTITIONS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_VALUES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SUB_LEXERS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SUB_LEXERS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SUB_LEXERS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SUB_LEXER_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SUB_LEXER_VALS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SUB_LEXER_VALS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_OBJECTS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_OBJECTS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_OBJECTS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_SQES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_SQES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_SQES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_SQES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_THESAURI','VIEW');
insert into ctxsys.dr$dbo values ('CTX_THESAURI','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_THESAURI','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_THESAURI','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_THES_PHRASES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_THES_PHRASES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_THES_PHRASES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_THES_PHRASES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_SECTION_GROUPS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_SECTION_GROUPS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_SECTION_GROUPS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_SECTION_GROUPS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_SECTIONS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_SECTIONS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_SECTIONS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_SECTIONS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_STOPLISTS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_STOPLISTS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_STOPLISTS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_STOPLISTS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_STOPWORDS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_STOPWORDS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_STOPWORDS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_STOPWORDS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_SUB_LEXERS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_SUB_LEXERS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_SUB_LEXERS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_SUB_LEXERS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SETS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SETS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SETS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SETS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SET_INDEXES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_INDEX_SET_INDEXES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SET_INDEXES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_SET_INDEXES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRV$PENDING','VIEW');
insert into ctxsys.dr$dbo values ('CTX_PENDING','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_PENDING','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_PENDING','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRV$WAITING','VIEW');
insert into ctxsys.dr$dbo values ('DRV$ONLINE_PENDING','VIEW');
insert into ctxsys.dr$dbo values ('DRV$DELETE','VIEW');
insert into ctxsys.dr$dbo values ('DRV$DELETE2','VIEW');
insert into ctxsys.dr$dbo values ('DRV$UNINDEXED','VIEW');
insert into ctxsys.dr$dbo values ('DRV$UNINDEXED2','VIEW');
insert into ctxsys.dr$dbo values ('CTX_INDEX_ERRORS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_ERRORS','VIEW');
insert into ctxsys.dr$dbo values ('CTX_USER_INDEX_ERRORS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_VERSION','VIEW');
insert into ctxsys.dr$dbo values ('CTX_TRACE_VALUES','VIEW');
insert into ctxsys.dr$dbo values ('CTX_TRACE_VALUES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRI_SUBLXV_LANG','FUNCTION');
insert into ctxsys.dr$dbo values ('DRI_VERSION','FUNCTION');
insert into ctxsys.dr$dbo values ('DRI_MOVE_CTXSYS','PROCEDURE');
insert into ctxsys.dr$dbo values ('DM_SVM_CUR','PACKAGE');
insert into ctxsys.dr$dbo values ('DMSVMBO','TYPE');
insert into ctxsys.dr$dbo values ('DMSVMBOS','TYPE');
insert into ctxsys.dr$dbo values ('DM_SVM_BUILD_DUMMY','FUNCTION');
insert into ctxsys.dr$dbo values ('DM_SVM_BUILD','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DMSVMAO','TYPE');
insert into ctxsys.dr$dbo values ('DMSVMAOS','TYPE');
insert into ctxsys.dr$dbo values ('DM_SVM_APPLY_DUMMY','FUNCTION');
insert into ctxsys.dr$dbo values ('DM_SVM_APPLY','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('ODM_UTIL_DUMMY','PACKAGE');
insert into ctxsys.dr$dbo values ('ODM_UTIL','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DM_CL_CUR','PACKAGE');
insert into ctxsys.dr$dbo values ('DMCLBO','TYPE');
insert into ctxsys.dr$dbo values ('DMCLBOS','TYPE');
insert into ctxsys.dr$dbo values ('DM_CL_BUILD_DUMMY','FUNCTION');
insert into ctxsys.dr$dbo values ('DM_CL_BUILD','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DM_CHILD','TYPE');
insert into ctxsys.dr$dbo values ('DM_CHILDREN','TYPE');
insert into ctxsys.dr$dbo values ('DM_CENTROID_DUMMY','TYPE');
insert into ctxsys.dr$dbo values ('DM_CENTROIDS_DUMMY','TYPE');
insert into ctxsys.dr$dbo values ('DM_CENTROIDS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DM_HISTOGRAM_BIN','TYPE');
insert into ctxsys.dr$dbo values ('DM_HISTOGRAMS','TYPE');
insert into ctxsys.dr$dbo values ('DM_PREDICATE','TYPE');
insert into ctxsys.dr$dbo values ('DM_PREDICATES','TYPE');
insert into ctxsys.dr$dbo values ('DM_RULE','TYPE');
insert into ctxsys.dr$dbo values ('DM_CLUSTER','TYPE');
insert into ctxsys.dr$dbo values ('DM_CLUSTERS','TYPE');
insert into ctxsys.dr$dbo values ('DBMS_DATA_MINING_DUMMY','PACKAGE');
insert into ctxsys.dr$dbo values ('DBMS_DATA_MINING','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DR$SESSION_STATE_T','TYPE');
insert into ctxsys.dr$dbo values ('DR$OPTIM_STATE_T','TYPE');
insert into ctxsys.dr$dbo values ('DR$POPINDEX_STATE_T','TYPE');
insert into ctxsys.dr$dbo values ('DR$CREATEINDEX_STATE_T','TYPE');
insert into ctxsys.dr$dbo values ('DR$TRC_REC','TYPE');
insert into ctxsys.dr$dbo values ('DR$TRC_TAB','TYPE');
insert into ctxsys.dr$dbo values ('DR$LIB','LIBRARY');
insert into ctxsys.dr$dbo values ('TEXTINDEXMETHODS','TYPE');
insert into ctxsys.dr$dbo values ('TEXTINDEXMETHODS','TYPE BODY');
insert into ctxsys.dr$dbo values ('TEXTOPTSTATS','TYPE');
insert into ctxsys.dr$dbo values ('CATINDEXMETHODS','TYPE');
insert into ctxsys.dr$dbo values ('CATINDEXMETHODS','TYPE BODY');
insert into ctxsys.dr$dbo values ('RULEINDEXMETHODS','TYPE');
insert into ctxsys.dr$dbo values ('RULEINDEXMETHODS','TYPE BODY');
insert into ctxsys.dr$dbo values ('XPATHINDEXMETHODS','TYPE');
insert into ctxsys.dr$dbo values ('XPATHINDEXMETHODS','TYPE BODY');
insert into ctxsys.dr$dbo values ('CTX_CONTAINS','PACKAGE');
insert into ctxsys.dr$dbo values ('CONTAINS','OPERATOR');
insert into ctxsys.dr$dbo values ('CONTAINS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRISCORE','PACKAGE');
insert into ctxsys.dr$dbo values ('SCORE','OPERATOR');
insert into ctxsys.dr$dbo values ('SCORE','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CONTEXT','INDEXTYPE');
insert into ctxsys.dr$dbo values ('CONTEXT','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('SYNCRN','PROCEDURE');
insert into ctxsys.dr$dbo values ('CTX_CATSEARCH','PACKAGE');
insert into ctxsys.dr$dbo values ('CATSEARCH','OPERATOR');
insert into ctxsys.dr$dbo values ('CATSEARCH','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTXCAT','INDEXTYPE');
insert into ctxsys.dr$dbo values ('CTXCAT','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_MATCHES','PACKAGE');
insert into ctxsys.dr$dbo values ('MATCHES','OPERATOR');
insert into ctxsys.dr$dbo values ('MATCHES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRISCORR','PACKAGE');
insert into ctxsys.dr$dbo values ('MATCH_SCORE','OPERATOR');
insert into ctxsys.dr$dbo values ('MATCH_SCORE','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTXRULE','INDEXTYPE');
insert into ctxsys.dr$dbo values ('CTXRULE','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_XPCONTAINS','PACKAGE');
insert into ctxsys.dr$dbo values ('XPCONTAINS','OPERATOR');
insert into ctxsys.dr$dbo values ('CTXXPATH','INDEXTYPE');
insert into ctxsys.dr$dbo values ('CTXXPATH','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRIOBJ', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DR_DEF', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIG', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIACC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRICON', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIDISP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIDML', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIDOC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIERR', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIEXP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIIMP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIIXS', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRILIST', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRILOAD', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIMLX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIOPT', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIPARSE', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIPREF', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIREC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIREP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIREPM', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIREPZ', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRISGP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRISPL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRITHS', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRITHSC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRITHSD', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRITHSL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRITHSX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIUTL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIVAL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIXMD', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDISP', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDDL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDDLC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDDLR', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDDLX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDML', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVDOC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRUE', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVIMR', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIPARX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVODM', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVPARX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVTMT', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVUTL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVXMD', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVXTAB', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVXTABC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVXTABR', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRVXTABX', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRV0DDL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_ADM', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_DDL', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_DOC', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_OUTPUT', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_QUERY', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_THES', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_REPORT', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_ULEXER', 'PACKAGE');
insert into ctxsys.dr$dbo values ('CTX_CLS', 'PACKAGE');
insert into ctxsys.dr$dbo values ('DRIACC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRICON', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIDISP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIDML', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIDOC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIERR', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIEXP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIIMP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIIXS', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRILOAD', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIMLX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIOPT', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIPARSE', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIPREF', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIREC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIREP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIREPM', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIREPZ', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRISGP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRISPL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRITHS', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRITHSC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRITHSD', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRITHSL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRITHSX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIUTL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIVAL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIXMD', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDISP', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDDL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDDLC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDDLR', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDDLX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDML', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVDOC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRUE', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVIMR', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRIPARX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVODM', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVPARX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVTMT', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVUTL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVXMD', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVXTAB', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVXTABC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVXTABR', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRVXTABX', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('DRV0DDL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_ADM', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_DDL', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_DOC', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_OUTPUT', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_QUERY', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_THES', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_REPORT', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_CLS', 'PACKAGE BODY');
insert into ctxsys.dr$dbo values ('CTX_DOC','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_DDL','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_OUTPUT','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_QUERY','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_THES','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_REPORT','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_ULEXER','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('CTX_CLS','PUBLIC SYNONYM');
insert into ctxsys.dr$dbo values ('DRVODM','PUBLIC SYNONYM');
commit;
