/*
 * Copyright (c) 2009,2010 Serhiy Kulyk
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * SQL CODE ASSISTANT PLUG-IN FOR INTELLIJ IDEA IS PROVIDED BY SERHIY KULYK
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL SERHIY KULYK BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.deepsky.view.schema_pane.ui;

import com.deepsky.lang.plsql.objTree.DbElementRoot;
import com.deepsky.lang.plsql.objTree.DbTreeElement;
import com.deepsky.lang.plsql.objTree.DetailsTableModel;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import java.awt.*;

public class GenericTabForm extends TabFormBaseWrapper {
    private JPanel rootPanel;
    private JTree centralTree;
    private JTabbedPane tabbedPane1;
    private JTable detailsTable;
    private JSplitPane splitPane;
    private JPanel bottomPanel;
    private JPanel top;

    DbElementRoot packageType;

    public GenericTabForm(DbElementRoot tableType) {
        this.packageType = tableType;

        rootPanel.putClientProperty(TEST501_COMPONENT, this);
        init(tableType);
    }

    public JComponent getRootPanel() {
        return rootPanel;
    }

    @Override
    public JPanel getTopPanel() {
        return top;
    }

    @Override
    public JTree getCentralTree() {
        return centralTree;
    }

    public JSplitPane getSplitPane() {
        return splitPane;
    }

    protected void updatePropertySheet(Object lastSelectedComponent) {
        // update Detail Tab
        TableModel properties;
        if (lastSelectedComponent != null) {
            properties = ((DbTreeElement) lastSelectedComponent).getProperties();
        } else {
            properties = new DetailsTableModel(new String[]{});
        }

        detailsTable.setModel(properties);
/*
        for (int i = 0; i < detailsTable.getColumnCount(); i++) {
            packColumn(detailsTable, i, 1);
        }
*/

        bottomPanel.validate();
    }

/*
    final int ROWNUM_TO_MAKE_DECISION = 8;
    final int MAX_WIDTH = 200;

    private void packColumn(JTable table, int colIndex, int margin) {
        int colHeaderWidth = getColumnHeaderWidth(table, colIndex);
        int colCellWidth = getColumnCellWidth(table, colIndex);

        int width = Math.max(colHeaderWidth, colCellWidth);
        width += 2 * margin;
        TableColumn column = table.getColumnModel().getColumn(colIndex);
        column.setPreferredWidth((width > MAX_WIDTH) ? MAX_WIDTH : width);
    }

    private int getColumnCellWidth(JTable table, int colIndex) {
        int width = 0;
        for (int r = 0; r < table.getRowCount() && r < ROWNUM_TO_MAKE_DECISION; r++) {
            TableCellRenderer renderer = table.getCellRenderer(r, colIndex);
            Component comp = renderer.getTableCellRendererComponent(
                    table, table.getValueAt(r, colIndex), false, false, r, colIndex);
            width = Math.max(width, comp.getPreferredSize().width);
        }

        return width;
    }

    private int getColumnHeaderWidth(JTable table, int colIndex) {
        TableColumn col = table.getColumnModel().getColumn(colIndex);
        TableCellRenderer renderer = col.getHeaderRenderer();
        if (renderer == null)
            renderer = table.getTableHeader().getDefaultRenderer();
        Component comp = renderer.getTableCellRendererComponent(table, col.getHeaderValue(), false, false, 0, 0);
        return comp.getPreferredSize().width;
    }
*/


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        splitPane = new JSplitPane();
        splitPane.setOrientation(0);
        rootPanel.add(splitPane, BorderLayout.CENTER);
        top = new JPanel();
        top.setLayout(new BorderLayout(0, 0));
        splitPane.setLeftComponent(top);
        final JScrollPane scrollPane1 = new JScrollPane();
        top.add(scrollPane1, BorderLayout.CENTER);
        centralTree = new JTree();
        centralTree.setRootVisible(false);
        centralTree.setShowsRootHandles(true);
        scrollPane1.setViewportView(centralTree);
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new BorderLayout(0, 0));
        splitPane.setRightComponent(bottomPanel);
        tabbedPane1 = new JTabbedPane();
        bottomPanel.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Properties", panel1);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel1.add(scrollPane2, BorderLayout.CENTER);
        detailsTable = new JTable();
        scrollPane2.setViewportView(detailsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}